[args]
debugging_mode = false
client_id = 12345
client_secret = "abcde"
redirect_url = "https://example.com:8501"
admins = []  # List of user IDs, perm lvl 4
ops = []  # List of user IDs, perm lvl 3
api_key = ""

[connections.osuawa]
url = "sqlite:///osuawa.db"
